const FIFA23Teams = [
    // Premier League
    { name: "Arsenal", code: "ARS" },
    { name: "Aston Villa", code: "AVL" },
    { name: "Bournemouth", code: "BOU" },
    { name: "Brentford", code: "BRE" },
    { name: "Brighton & Hove Albion", code: "BHA" },
    { name: "Chelsea", code: "CHE" },
    { name: "Crystal Palace", code: "CRY" },
    { name: "Everton", code: "EVE" },
    { name: "Fulham", code: "FUL" },
    { name: "Leeds United", code: "LEE" },
    { name: "Leicester City", code: "LEI" },
    { name: "Liverpool", code: "LIV" },
    { name: "Manchester City", code: "MCI" },
    { name: "Manchester United", code: "MUN" },
    { name: "Newcastle United", code: "NEW" },
    { name: "Nottingham Forest", code: "NFO" },
    { name: "Southampton", code: "SOU" },
    { name: "Tottenham Hotspur", code: "TOT" },
    { name: "West Ham United", code: "WHU" },
    { name: "Wolverhampton Wanderers", code: "WOL" },
  
    // La Liga
    { name: "Athletic Club de Bilbao", code: "ATH" },
    { name: "Atlético de Madrid", code: "ATM" },
    { name: "FC Barcelona", code: "BAR" },
    { name: "Real Betis", code: "BET" },
    { name: "Cádiz CF", code: "CAD" },
    { name: "Celta de Vigo", code: "CEL" },
    { name: "Elche CF", code: "ELC" },
    { name: "Espanyol", code: "ESP" },
    { name: "Getafe CF", code: "GET" },
    { name: "Girona FC", code: "GIR" },
    { name: "Mallorca", code: "MAL" },
    { name: "Osasuna", code: "OSA" },
    { name: "Rayo Vallecano", code: "RAY" },
    { name: "Real Madrid", code: "RMA" },
    { name: "Real Sociedad", code: "RSO" },
    { name: "Sevilla FC", code: "SEV" },
    { name: "Valencia CF", code: "VAL" },
    { name: "Valladolid", code: "VLL" },
    { name: "Villarreal CF", code: "VIL" },
  
    // Bundesliga
    { name: "FC Augsburg", code: "AUG" },
    { name: "Bayer 04 Leverkusen", code: "B04" },
    { name: "Bayern München", code: "BAY" },
    { name: "VfL Bochum", code: "BOC" },
    { name: "Borussia Dortmund", code: "BVB" },
    { name: "Borussia Mönchengladbach", code: "BMG" },
    { name: "Eintracht Frankfurt", code: "SGE" },
    { name: "SC Freiburg", code: "SCF" },
    { name: "Hertha BSC", code: "BSC" },
    { name: "1899 Hoffenheim", code: "TSG" },
    { name: "1. FC Köln", code: "KOE" },
    { name: "1. FSV Mainz 05", code: "M05" },
    { name: "RB Leipzig", code: "RBL" },
    { name: "FC Schalke 04", code: "S04" },
    { name: "VfB Stuttgart", code: "VFB" },
    { name: "Union Berlin", code: "FCU" },
    { name: "Werder Bremen", code: "SVW" },
    { name: "VfL Wolfsburg", code: "WOB" },
  
    // Serie A
    { name: "Atalanta", code: "ATA" },
    { name: "Bologna", code: "BOL" },
    { name: "Cremonese", code: "CRE" },
    { name: "Empoli", code: "EMP" },
    { name: "Fiorentina", code: "FIO" },
    { name: "Hellas Verona", code: "HEL" },
    { name: "Inter", code: "INT" },
    { name: "Juventus", code: "JUV" },
    { name: "Lazio", code: "LAZ" },
    { name: "Lecce", code: "LEC" },
    { name: "AC Milan", code: "MIL" },
    { name: "Monza", code: "MON" },
    { name: "Napoli", code: "NAP" },
    { name: "Roma", code: "ROM" },
    { name: "Salernitana", code: "SAL" },
    { name: "Sampdoria", code: "SAM" },
    { name: "Sassuolo", code: "SAS" },
    { name: "Spezia", code: "SPE" },
    { name: "Torino", code: "TOR" },
    { name: "Udinese", code: "UDI" },
  
    // Ligue 1
    { name: "AC Ajaccio", code: "ACA" },
    { name: "Angers SCO", code: "ANG" },
    { name: "AJ Auxerre", code: "AUX" },
    { name: "Stade Brestois 29", code: "BRE" },
    { name: "Clermont Foot 63", code: "CLF" },
    { name: "RC Lens", code: "RCL" },
    { name: "LOSC Lille", code: "LIL" },
    { name: "FC Lorient", code: "LOR" },
    { name: "Olympique Lyonnais", code: "OL" },
    { name: "Olympique de Marseille", code: "OM" },
    { name: "AS Monaco", code: "ASM" },
    { name: "Montpellier HSC", code: "MHS" },
    { name: "FC Nantes", code: "NAN" },
    { name: "OGC Nice", code: "NIC" },
    { name: "Paris Saint-Germain", code: "PSG" },
    { name: "Stade de Reims", code: "REI" },
    { name: "Stade Rennais FC", code: "REN" },
    { name: "RC Strasbourg Alsace", code: "RCS" },
    { name: "Toulouse FC", code: "TOU" },
    { name: "ESTAC Troyes", code: "TRO" },
  
    // Other notable teams
    { name: "Ajax", code: "AJA" },
    { name: "PSV Eindhoven", code: "PSV" },
    { name: "Feyenoord", code: "FEY" },
    { name: "Porto", code: "POR" },
    { name: "Benfica", code: "BEN" },
    { name: "Sporting CP", code: "SCP" },
    { name: "Celtic", code: "CEL" },
    { name: "Rangers", code: "RAN" },
    { name: "Shakhtar Donetsk", code: "SHA" },
    { name: "Dynamo Kyiv", code: "DYK" },
    { name: "Zenit St. Petersburg", code: "ZEN" },
    { name: "CSKA Moscow", code: "CSK" },
    { name: "Galatasaray", code: "GAL" },
    { name: "Fenerbahçe", code: "FEN" },
    { name: "Beşiktaş", code: "BES" },
  ];

// International Teams
const FIFA23InternationalTeams = [
  // UEFA (Europe)
  { name: "England", code: "ENG" },
  { name: "France", code: "FRA" },
  { name: "Germany", code: "GER" },
  { name: "Spain", code: "ESP" },
  { name: "Italy", code: "ITA" },
  { name: "Portugal", code: "POR" },
  { name: "Netherlands", code: "NED" },
  { name: "Belgium", code: "BEL" },
  { name: "Croatia", code: "CRO" },
  { name: "Denmark", code: "DEN" },
  { name: "Sweden", code: "SWE" },
  { name: "Poland", code: "POL" },
  { name: "Wales", code: "WAL" },
  { name: "Switzerland", code: "SUI" },
  { name: "Austria", code: "AUT" },
  { name: "Ukraine", code: "UKR" },
  { name: "Serbia", code: "SRB" },
  { name: "Turkey", code: "TUR" },
  { name: "Czech Republic", code: "CZE" },
  { name: "Scotland", code: "SCO" },

  // CONMEBOL (South America)
  { name: "Brazil", code: "BRA" },
  { name: "Argentina", code: "ARG" },
  { name: "Uruguay", code: "URU" },
  { name: "Colombia", code: "COL" },
  { name: "Chile", code: "CHI" },
  { name: "Peru", code: "PER" },
  { name: "Paraguay", code: "PAR" },
  { name: "Ecuador", code: "ECU" },
  { name: "Venezuela", code: "VEN" },
  { name: "Bolivia", code: "BOL" },

  // CONCACAF (North and Central America, Caribbean)
  { name: "Mexico", code: "MEX" },
  { name: "United States", code: "USA" },
  { name: "Canada", code: "CAN" },
  { name: "Costa Rica", code: "CRC" },
  { name: "Jamaica", code: "JAM" },
  { name: "Honduras", code: "HON" },
  { name: "Panama", code: "PAN" },

  // CAF (Africa)
  { name: "Senegal", code: "SEN" },
  { name: "Morocco", code: "MAR" },
  { name: "Nigeria", code: "NGA" },
  { name: "Egypt", code: "EGY" },
  { name: "Cameroon", code: "CMR" },
  { name: "Ghana", code: "GHA" },
  { name: "Algeria", code: "ALG" },
  { name: "Tunisia", code: "TUN" },
  { name: "Côte d'Ivoire", code: "CIV" },

  // AFC (Asia)
  { name: "Japan", code: "JPN" },
  { name: "South Korea", code: "KOR" },
  { name: "Australia", code: "AUS" },
  { name: "Iran", code: "IRN" },
  { name: "Saudi Arabia", code: "KSA" },
  { name: "Qatar", code: "QAT" },

  // OFC (Oceania)
  { name: "New Zealand", code: "NZL" },
];

// Combine club and international teams
const FIFA23AllTeams = [...FIFA23Teams, ...FIFA23InternationalTeams];

export { FIFA23Teams, FIFA23InternationalTeams, FIFA23AllTeams };